### ISSUE TITLE
Support OMERO 5.5.x and 5.4.x servers

### ISSUE THREAD

**Issue by will-moore** [ome/omero-downloader#29]
See https://forum.image.sc/t/batch-export-entire-projects-in-omero/30172/8?u=will-moore

Since there are still lots of 5.4.x servers out there, would it be asking too much for an up-to-date 5.4.x-compatible version?

cc @dsudar

**Comment by pwalczysko** [comment]
This version of omero-downloader https://github.com/ome/omero-downloader/releases/tag/v0.1.5 works with 5.4. servers. 

I think this issue here should rather concern the gaps in the doc - afaik, we do have a working 5.4 compatible downloader version, but I agree that this is hard to know from our docs.

cc @mtbc

**Comment by mtbc** [comment]
Further we'll need another release using https://github.com/ome/omero-gateway-java/pull/23 to accommodate both 5.5 and 5.6 servers.
