### ISSUE TITLE
Using omero-downloader on public Datasets

### ISSUE THREAD

**Issue by bisnow33** [ome/omero-downloader#47]
Hi, 

I try to use the script on public data published on this omero server : omero.bio.fsu.edu .  So i runned something like : 
./download.sh -b MY_PATH -s omero.bio.fsu.edu -f binary Dataset:5015
but it seems that user and password are required. 
I'm doing something wrong ? 
Do you know if there is a solution like default/public user i can give ? or other solution ? 

Best,

Tristan

**Comment by pwalczysko** [comment]
Hi @bisnow33 

I can see that you just closed the issue, did you find a solution for your problem ?
From our point of view, yes, the username and password would be necessary for what you are attempting, but because it is a public user password on that server, it is not a workflow which we would recommend, as it would be not prudent for an administrator of a typical OMERO.server to give out such password.

Please let us know the status, we can discuss further if you still need help.

Thank you

Petr, OME Team

**Comment by bisnow33** [comment]
Hi @pwalczysko

Thanks for this answer, i understand you point of view. I didn't resolved the problem and I'm still trying alternatives. We choose this way to be in real open source way (asking people to create an account for me is not ....) but may be omero is not the good plateform to share our data ... plus if it's not safe to give the public account.
So my real problems is that the http protocol transfer stop for large amount of data ... I don't know if the problem come from omero server answer of something else. I also tried to use omero insigth application but i think in this case account is required too ... 
If you got other ideas :)

Best

**Comment by joshmoore** [comment]
Hi @bisnow33,

Sorry for chiming in late.

I'll post some thoughs there but then we might want to move the conversation to https://forum.image.sc/c/data so that more people can participate. The issue you are running into does come up regularly, and we certainly understand the need, but being it's something that the team in Dundee hasn't had the time to solve, but of course, it's open source so there are (or can be) always new solutions!

 - An option with OMERO.downloader as it stands might be to give users a token that they can use to login remotely. You'd need to create the tokens somehow . omero-oauth might be an option. See https://forum.image.sc/t/installing-omero-oauth/45088/3 for an ongoing conversation.
 - @sukunis has just released https://github.com/sukunis/OMERO.openlink/releases/tag/v0.1.0 which is a tool to allow downloading directly from nginx. If that solves the performance issues, then you would know that nginx wasn't the bottleneck.
- Our focus recently has been on defining a format that's more suited for download. You can see examples on our blog at https://blog.openmicroscopy.org/file-formats/community/2020/11/04/zarr-data/ If you have the space (potentially on object storage) and would like to convert your data to a downloadable format, we're happy to help. (There's also a [microservice](https://github.com/ome/omero-ms-zarr) that will translate your data on the fly, but in it's current form it will make *all* your data public!)

All the best,
~Josh
